## **Numpy Indexing and Selection**

In [4]:
import numpy as np

Creating a sample array:

In [5]:
arr = np.arange(0,11)

Display the array:

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **Bracket Indexing and Selection**

Get a value at an index by calling `arr[]`

In [4]:
arr[8]

np.int64(8)

Get values in a range by calling `arr[:]`

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

### **Broadcasting**
NumPy lists differ from python lists because of their ability to **broadcast**.

In [8]:
# Setting a value with index range --> Broadcasting!
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr[0:5]

array([100, 100, 100, 100, 100])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Slicing Arrays
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
# Change Slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

The original array remains unchanged. This avoids memory problems.

To get a copy of an array, you need to be explicit by calling on `.copy()`

In [15]:
arr_copy = arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### **Indexing a 2D array (matrices)**

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

To get an individual element use: `arr_2d[index][index]` or `arr_2d[index,index]`

Comma notation is recommended for **clarity**.

In [32]:
# Getting individual element value
arr_2d[0][0]

np.int64(5)

In [38]:
# Getting individual element value
arr_2d[2,1]

np.int64(40)

In [19]:
# 2D array slicing
# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [21]:
# Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### **Selection**

Using brackets for selection based off of comparison operators.

In [53]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
bool_arr = arr > 5

In [56]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr<3]

array([1, 2])

In [60]:
arr_2d = np.arange(50).reshape(5,10)

In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [71]:
arr_2d[3:5,3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46]])

In [73]:
arr_2d[3:5,8:11]

array([[38, 39],
       [48, 49]])