In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:] = 100

In [28]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[0][0]

np.int64(5)

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[1][1]

np.int64(25)

In [35]:
arr_2d[2][2]

np.int64(45)

In [36]:
arr_2d[2][0]

np.int64(35)

In [37]:
arr_2d[2][1]

np.int64(40)

In [38]:
arr_2d[2,1]

np.int64(40)

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [49]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [51]:
arr = np.arange(1,11)

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
bool_arr = arr > 5

In [56]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr<3]

array([1, 2])

In [60]:
arr_2d = np.arange(50).reshape(5,10)

In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [71]:
arr_2d[3:5,3:7]

array([[33, 34, 35, 36],
       [43, 44, 45, 46]])

In [73]:
arr_2d[3:5,8:11]

array([[38, 39],
       [48, 49]])